import GaussianTensorExecution
import CommunityPrecisionProfile

#print axioms GaussianParity.GInt.ext
#print axioms GaussianParity.residue_zero_iff
#print axioms GaussianParity.dividePi_exact_iff
#print axioms GaussianParity.dividePi_mulPi
#print axioms GaussianParity.butterfly_integral_iff
#print axioms GaussianParity.butterfly_exact
#print axioms GaussianParity.butterfly_sameResidue
#print axioms GaussianParity.butterfly_square
#print axioms GaussianParity.residue_mulI
#print axioms GaussianParity.residue_add
#print axioms GaussianParity.residue_mulPi
#print axioms GaussianParity.component_parity_implies_sameResidue
#print axioms GaussianParity.cross_parity_example
#print axioms GaussianParity.changed_pairing_obstruction
#print axioms GaussianParity.piIter_mulPi
#print axioms GaussianParity.piIter_add
#print axioms GaussianParity.piIter_commute
#print axioms GaussianParity.mulPi_injective
#print axioms GaussianParity.piIter_injective
#print axioms GaussianParity.SameValue.refl
#print axioms GaussianParity.SameValue.symm
#print axioms GaussianParity.SameValue.trans
#print axioms GaussianParity.certifiedButterfly_contract
#print axioms GaussianParity.certifiedButterfly_refines
#print axioms GaussianParity.certifiedButterfly_exponent_bound
#print axioms GaussianParity.inverseButterfly_eq_swap
#print axioms GaussianParity.inverseButterfly_after
#print axioms GaussianParity.butterfly_fourth
#print axioms GaussianParity.doubleButterfly_joint_parity
#print axioms GaussianParity.sharedDefect_is_bit
#print axioms GaussianParity.sharedDefect_zero_iff
#print axioms GaussianParity.shared_defect_reconstruction
#print axioms GaussianParity.doubleButterfly_exact
#print axioms GaussianParity.halfHadamard_exact_iff
#print axioms GaussianParity.cross_parity_fails_halfHadamard
#print axioms GaussianParity.raiseTo_sameValue
#print axioms GaussianParity.alignedButterfly_input_exact
#print axioms GaussianParity.alignedButterfly_refines
#print axioms GaussianParity.mulPi_square
#print axioms GaussianParity.mulI_scale
#print axioms GaussianParity.scale_mul
#print axioms GaussianParity.repeatPi_even
#print axioms GaussianParity.mulI_negI
#print axioms GaussianParity.negI_mulI
#print axioms GaussianParity.repeatI_commute
#print axioms GaussianParity.repeatI_negI_commute
#print axioms GaussianParity.repeatI_cancel
#print axioms GaussianParity.mulPi_scale
#print axioms GaussianParity.repeatPi_odd
#print axioms GaussianParity.pi_even_ideal
#print axioms GaussianParity.pi_odd_ideal
#print axioms GaussianParity.odd_ideal_parity
#print axioms GaussianParity.pi_not_binary_one
#print axioms GaussianParity.even_binary_conversion
#print axioms GaussianParity.odd_binary_conversion
#print axioms GaussianParity.residue_negI
#print axioms GaussianParity.repeatNegI_residue
#print axioms GaussianParity.odd_binary_numerator_parity
#print axioms GaussianParity.binary_grid_conversion
#print axioms GaussianParity.binary_one_residue_zero
#print axioms GaussianParity.even_impulse_primitive
#print axioms GaussianParity.bothOdd_negI
#print axioms GaussianParity.bothOdd_repeatNegI
#print axioms GaussianParity.odd_impulse_primitive
#print axioms GaussianParity.scale_injective
#print axioms GaussianParity.even_grid_sharp
#print axioms GaussianParity.odd_grid_sharp
#print axioms GaussianParity.gaussianMul_pi_pi
#print axioms GaussianParity.two_pi_factors_binary
#print axioms GaussianSynthesis.cancelPi_sameValue
#print axioms GaussianSynthesis.normalizeCore_sound
#print axioms GaussianSynthesis.normalize_sound
#print axioms GaussianSynthesis.normalizeCore_canonical
#print axioms GaussianSynthesis.normalize_canonical
#print axioms GaussianSynthesis.normalize_fixed
#print axioms GaussianSynthesis.normalize_idempotent
#print axioms GaussianSynthesis.normalizeCore_exponent_bound
#print axioms GaussianSynthesis.normalize_zero
#print axioms GaussianSynthesis.positive_piIter_residue
#print axioms GaussianSynthesis.canonical_tags_equal
#print axioms GaussianSynthesis.canonical_unique
#print axioms GaussianSynthesis.normalize_congr
#print axioms GaussianSynthesis.mixed_center_image
#print axioms GaussianSynthesis.fresh_total_recovery
#print axioms GaussianSynthesis.fresh_doubled_center
#print axioms GaussianSynthesis.fresh_scatter_denominator_cancellation
#print axioms GaussianSynthesis.corrected_bulk_coefficient
#print axioms GaussianSynthesis.dirty_center_obstruction
#print axioms GaussianSynthesis.dirty_center_difference_is_fresh
#print axioms GaussianSynthesis.centerColumn_image
#print axioms GaussianSynthesis.centerPlus_image
#print axioms GaussianSynthesis.arbitrary_fresh_columns_image
#print axioms GaussianSynthesis.arbitrary_fresh_columns_total
#print axioms GaussianSynthesis.dirty_update_difference_image
#print axioms GaussianSynthesis.raw_dirty_update_defect
#print axioms GaussianSynthesis.corrected_scatter_column_exact
#print axioms GaussianSynthesis.corrected_scatter_sum_exact
#print axioms GaussianSynthesis.corrected_scatter_sum_integral
#print axioms GaussianSynthesis.fresh_bulk_half_sharp
#print axioms GaussianSynthesis.rawC_left_square
#print axioms GaussianSynthesis.rawC_right_square
#print axioms GaussianSynthesis.two_pi_numerator_sameValue
#print axioms GaussianSynthesis.rawC_square_exact
#print axioms GaussianSynthesis.rawC_inverse_exact
#print axioms GaussianSynthesis.heterogeneous_inverse_restores
#print axioms GaussianSynthesis.canonical_inverse_restores
#print axioms GaussianSynthesis.phase_inverse_restores
#print axioms GaussianSynthesis.half_double_restores
#print axioms GaussianSynthesis.gaussian_update_difference
#print axioms GaussianSynthesis.mulI_difference
#print axioms GaussianSynthesis.phase_difference
#print axioms GaussianSynthesis.matching_phase_dirty_difference
#print axioms GaussianSynthesis.mismatched_phase_image_obstruction
#print axioms GaussianSynthesis.producer_image_iff_roundtrip
#print axioms GaussianSynthesis.producer_projection_idempotent
#print axioms GaussianSynthesis.image_difference_recovers
#print axioms GaussianSynthesis.recoverIfImage_exact
#print axioms GaussianSynthesis.recoverIfImage_rejects
#print axioms GaussianSynthesis.certified_dirty_recovery_and_restore
#print axioms GaussianSynthesis.phase_scale
#print axioms GaussianSynthesis.common_phase_center_image
#print axioms GaussianSynthesis.per_role_phase_image_obstruction
#print axioms GaussianSynthesis.canonical_tag_minimal
#print axioms GaussianSynthesis.normalized_tag_minimal
#print axioms CommunityPrecision.ceilHalf_subadditive
#print axioms CommunityPrecision.ceilHalf_mul_bound
#print axioms CommunityPrecision.arbitrary_profile_bound
#print axioms CommunityPrecision.profile_rank_mass
#print axioms CommunityPrecision.profile_odd_multiplicity
#print axioms CommunityPrecision.profile_precision_charge
#print axioms CommunityPrecision.profile_call_count
#print axioms CommunityPrecision.certified_all_width_bound
#print axioms CommunityPrecision.profile_saving
#print axioms GaussianTensorExecution.cubeMap_congr
#print axioms GaussianTensorExecution.cubeMap_comp
#print axioms GaussianTensorExecution.cubeMap_zip
#print axioms GaussianTensorExecution.mulPi_add
#print axioms GaussianTensorExecution.mulPi_mulI
#print axioms GaussianTensorExecution.cubePi_add
#print axioms GaussianTensorExecution.cubePi_I
#print axioms GaussianTensorExecution.axisForward_pi
#print axioms GaussianTensorExecution.axisInverse_pi
#print axioms GaussianTensorExecution.inverse_pi
#print axioms GaussianTensorExecution.cubePiIter_succ
#print axioms GaussianTensorExecution.cubePiIter_add
#print axioms GaussianTensorExecution.cube_ext
#print axioms GaussianTensorExecution.get_map
#print axioms GaussianTensorExecution.get_zip
#print axioms GaussianTensorExecution.cubeMap_id
#print axioms GaussianTensorExecution.inverse_piIter
#print axioms GaussianTensorExecution.axis_inverse_forward
#print axioms GaussianTensorExecution.inverse_forward
#print axioms GaussianTensorExecution.shifted_tag_sameValue
#print axioms GaussianTensorExecution.inverse_forward_leaf_sameValue
#print axioms GaussianTensorExecution.inverse_forward_leaf_canonical
#print axioms GaussianTensorExecution.repeatPi_eq_piIter
#print axioms GaussianTensorExecution.forward_leaf_binary_grid
#print axioms GaussianTensorExecution.cubeI_zero
#print axioms GaussianTensorExecution.cubeAdd_zero_left
#print axioms GaussianTensorExecution.forward_zero
#print axioms GaussianTensorExecution.forward_impulse_first
#print axioms GaussianTensorExecution.forward_even_grid_sharp
#print axioms GaussianTensorExecution.forward_odd_grid_sharp
#print axioms GaussianTensorExecution.execute_inverse_forward_exact
#print axioms GaussianTensorExecution.execute_inverse_forward_canonical
#print axioms GaussianTensorExecution.execute_forward_tag
#print axioms GaussianTensorExecution.forward_binary_input_grid
#print axioms GaussianTensorExecution.forward_odd_binary_sublattice
