"""Pinned PR46 mixed-center image and dirty finite-difference scalar audit.

This is a reference scalar rewrite in one common frame. It does not compile
phase-frame transfers, tapes, or a new multiplication complexity bound.
The archived binary DAG is generated by credited upstream code; its integer
linear image is checked here independently with two coefficient bitplanes.
"""
from pathlib import Path
from itertools import combinations
from fractions import Fraction as Q
from random import Random
import array, argparse, hashlib, importlib, json, struct, subprocess, sys, time

PIN = "71b6c960c89295e952522dd44111df9cfc51ae90"
REQUIRED_SOURCES = [
    'scripts/structured_bulk/complex.py','scripts/structured_bulk/__init__.py',
    'scripts/paired_triple_circuit.py','scripts/paired_exclusion_circuit.py',
    'scripts/exclusion_circuit.py','scripts/partial_swap/binary.py',
    'scripts/partial_swap/__init__.py','notes/copied-centers-complex.tex',
    'notes/copied-centers-lemma.tex','notes/structured-bulk-complex.tex',
    'certificates/copied-centers-complex-input.json','LICENSE','NOTICE']

def need(h, message):
    if not h: raise AssertionError(message)

def sha(path): return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def add(a,b): return a[0]+b[0],a[1]+b[1]
def sub(a,b): return a[0]-b[0],a[1]-b[1]
def sc(k,z): return k*z[0],k*z[1]
def total(zs):
    out=(0,0)
    for z in zs: out=add(out,z)
    return out
def frac(z,n): return Q(z[0],n),Q(z[1],n)
def exact(z,n):
    need(all(x % n == 0 for x in z), "illegal exact division")
    return z[0]//n,z[1]//n
def grid_bits(z):
    return max(Q(x).denominator.bit_length()-1 for x in z)

def read_array(f,code,n):
    a=array.array(code); need(a.itemsize=={'I':4,'Q':8,'B':1}[code],"array width")
    a.frombytes(f.read(n*a.itemsize)); need(len(a)==n,"truncated array")
    if sys.byteorder != 'little' and a.itemsize>1: a.byteswap()
    return a

def read_dag(path):
    with open(path,'rb') as f:
        h,v,n,q=struct.unpack('<4I',f.read(16))
        args=read_array(f,'I',2*n)
        core=read_array(f,'Q',n); cover=read_array(f,'Q',n)
        roots=read_array(f,'I',q); kinds=read_array(f,'I',q)
        active=read_array(f,'B',n); need(not f.read(),"trailing DAG data")
    with open(str(path).removesuffix('.bin')+'.labels','rb') as f:
        ranks=read_array(f,'I',n); types=read_array(f,'B',n)
        need(not f.read(),"trailing labels")
    return dict(h=h,v=v,n=n,q=q,args=args,roots=roots,kinds=kinds,active=active,
                core=core,cover=cover,ranks=ranks,types=types)

def check_image(g,d):
    h,v,n=g['h'],g['v'],g['n']; ts=list(combinations(range(h),3))
    need(v==len(ts),"wrong input count")
    planes1=[0]*n; planes2=[0]*n; ordinary=centers=0
    for j in range(v): planes1[j+1]=1<<j
    for x in range(v+1,n):
        a,b=g['args'][2*x:2*x+2]
        need(0<a<x and 0<b<x,"non-topological addition")
        a1,b1,a2,b2=planes1[a],planes1[b],planes2[a],planes2[b]
        need(not(a2&(b1|b2) or b2&(a1|a2)),"coefficient exceeds two")
        planes1[x]=a1^b1; planes2[x]=a2|b2|(a1&b1)
        if g['types'][x] == 3: centers+=1
        else:
            need(not planes2[x],"ordinary addition contains coefficient two")
            ordinary+=1
    masks=[sum(1<<j for j,t in enumerate(ts) if i in t) for i in range(h)]
    full=(1<<v)-1; roots=g['roots']; roles={}; k=0
    for t in ts:
        roles['A',t]=k; x=roots[k]; k+=1
        expected=full & ~(masks[t[0]]|masks[t[1]]|masks[t[2]])
        need((planes1[x],planes2[x])==(expected,0),"wrong disjoint root")
    for a,b in combinations(range(h),2):
        for i in range(h):
            if i in (a,b): continue
            roles['E',(a,b,i)]=k; x=roots[k]; k+=1
            need((planes1[x],planes2[x])==(masks[a]&masks[b]&~masks[i],0),
                 "wrong pair-star root")
    for i in range(d,h):
        roles['B',i]=k; x=roots[k]; k+=1
        need((planes1[x],planes2[x])==(0,masks[i]),"wrong doubled center")
    for i in range(d):
        roles['D',i]=k; x=roots[k]; k+=1
        need((planes1[x],planes2[x])==(full&~masks[i],0),"wrong disjoint center")
    need(k==g['q'] and g['kinds'][:v].count(0)==v,"wrong role layout")
    # Universal coefficient check: no particular numeric inputs are used.
    # j=|source intersect target|; the corrected coefficient is
    # (j-1+[j=0]-[j=2])/2, exactly the identity coefficient.
    checked=0
    source_bits=[sum(1<<i for i in t) for t in ts]
    for target in source_bits:
        for source in source_bits:
            j=(target&source).bit_count()
            need(j-1+int(j==0)-int(j==2)==2*int(target==source),
                 "incorrect completed scalar coefficient")
            checked+=1
    return roles,ts,dict(nodes=n,addition_nodes=n-v-1,ordinary_additions=ordinary,
        center_additions=centers,root_roles=k,all_input_coefficient_pairs=checked,
        active_addition_nodes=sum(bool(g['active'][x]) for x in range(v+1,n)),
        coefficient_planes="exact 0/1/2 integer coefficients, no modular arithmetic",
        largest_coefficient=2)

def numeric_roots(g,xs):
    need(len(xs)==g['v'],"wrong producer source count")
    values=[(0,0)]*g['n']
    values[1:1+g['v']]=xs
    for x in range(g['v']+1,g['n']):
        a,b=g['args'][2*x:2*x+2]; values[x]=add(values[a],values[b])
    return [values[x] for x in g['roots']]

def generic_scatter(vals,roles,ts,h,d):
    B={i:vals[roles['B',i]] for i in range(d,h)}
    D={i:vals[roles['D',i]] for i in range(d)}
    T=frac(sub(total(B.values()),sc(2,total(D.values()))),2*(3-d))
    T_half=sc(Q(1,2),T)
    B_quarter={i:frac(z,4) for i,z in B.items()}
    D_half={i:frac(z,2) for i,z in D.items()}
    side_half={k:frac(vals[idx],2) for k,idx in roles.items() if k[0] in ('A','E')}
    bits=max([grid_bits(T),grid_bits(T_half)] +
             [grid_bits(z) for z in B_quarter.values()] +
             [grid_bits(z) for z in D_half.values()] +
             [grid_bits(z) for z in side_half.values()])
    out=[]
    for t in ts:
        k=sum(i<d for i in t)
        z=sub(total(B_quarter[i] for i in t if i>=d),
              total(D_half[i] for i in t if i<d))
        z=add(z,sc(k-1,T_half)); z=add(z,side_half['A',t])
        for a,b in combinations(t,2):
            i=next(j for j in t if j not in (a,b))
            z=sub(z,side_half['E',(a,b,i)])
        bits=max(bits,grid_bits(z)); out.append(z)
    return out,bits

def image_conditioned_fused_delta_fastpath(before,after,roles,ts,h,d):
    need(len(before)==len(after)==len(roles),"wrong complete producer port count")
    need(all(len(z)==2 and all(type(t) is int for t in z)
             for values in (before,after) for z in values),
         "Gaussian integer numerator pairs required")
    """Exact rewrite under the caller-supplied premise after-before=P(X).

    Local exact quotient assertions alone are NOT an image membership test.
    """
    delta=[sub(y,x) for x,y in zip(before,after)]
    B={i:delta[roles['B',i]] for i in range(d,h)}
    D={i:delta[roles['D',i]] for i in range(d)}
    T=exact(sub(total(B.values()),sc(2,total(D.values()))),2*(3-d))
    G={i:exact(B[i],2) for i in B}
    G.update({i:sub(T,D[i]) for i in D})
    out=[]
    for t in ts:
        z=add(sub(total(G[i] for i in t),T),delta[roles['A',t]])
        for a,b in combinations(t,2):
            i=next(j for j in t if j not in (a,b))
            z=sub(z,delta[roles['E',(a,b,i)]])
        out.append(exact(z,2))
    return out

def checked_fused_delta(g,before,after,roles,ts,h,d):
    """Full membership guard. The extra producer evaluation is paid work.

    Since QP=I on Gaussian input vectors, delta is in the Gaussian integer
    producer image iff P(Q(delta))=delta, provided Q(delta) is integral.
    """
    need(h==g['h'] and len(roles)==g['q'] and
         len(before)==len(after)==g['q'],"producer graph/port schema differs")
    candidate=image_conditioned_fused_delta_fastpath(before,after,roles,ts,h,d)
    delta=[sub(y,x) for x,y in zip(before,after)]
    need(numeric_roots(g,candidate)==delta,"delta is not in producer image")
    return candidate

def main():
    need(not sys.flags.optimize,'run without Python -O: pinned producer assertions must remain enabled')
    package=Path(__file__).resolve().parent
    parser=argparse.ArgumentParser()
    parser.add_argument('--upstream',type=Path,default=None,
        help='external Git checkout at the pinned PR46 head; default: bundled references/pr46')
    parser.add_argument('--sources',type=Path,default=package/'SOURCES.json',
        help='mandatory expected source SHA-256 manifest')
    parser.add_argument('--output',type=Path,required=True); a=parser.parse_args()
    external=a.upstream is not None
    if not external: a.upstream=package/'references/pr46'
    a.output.mkdir(parents=True,exist_ok=True)
    h,d=28,19; started=time.perf_counter()
    manifest=json.loads(a.sources.read_text(encoding='utf-8-sig'))
    need(manifest['upstream_commit']==PIN,'manifest differs from pinned PR46')
    expected_hashes=manifest['source_sha256']
    need(all(p in expected_hashes for p in REQUIRED_SOURCES),'source manifest omits a required dependency')
    for p,expected in expected_hashes.items():
        path=(a.upstream/p).resolve()
        need(path.is_relative_to(a.upstream.resolve()),'source path escapes bundle')
        need(sha(path)==expected,'source SHA-256 mismatch: '+p)
    if external:
        actual_pin=subprocess.check_output(['git','-C',str(a.upstream),'rev-parse','HEAD'],text=True).strip()
        need(actual_pin==PIN,"source checkout differs from pinned PR46")
    sys.path.insert(0,str(a.upstream/'scripts'))
    producer=importlib.import_module('structured_bulk.complex')
    prefix=a.output/'mixed28'; generated=producer.build(h,prefix,d,base=2)
    selected=json.loads((a.upstream/'certificates/copied-centers-complex-input.json').read_text())
    for field in ('h','v','c','q','loss','central_disjoint'):
        need(generated[field]==selected[field],'selected producer count differs: '+field)
    need(generated['R']==selected['baseline_R'],'scalar unmatched role count differs')
    g=read_dag(str(prefix)+'.bin'); roles,ts,image=check_image(g,d)
    rng=Random(46045); controls=[]; generic_max=0
    for trial in range(6):
        xs=[(rng.randint(-31,31),rng.randint(-31,31)) for _ in ts]
        if trial==0: xs=[(1,0)]+[(0,0)]*(len(ts)-1)
        fresh=numeric_roots(g,xs)
        dirty=[(rng.randint(-2**18,2**18),rng.randint(-2**18,2**18)) for _ in fresh]
        updated=[add(x,y) for x,y in zip(dirty,fresh)]
        oldout=[(rng.randint(-99,99),rng.randint(-99,99)) for _ in ts]
        f0,q0=generic_scatter(dirty,roles,ts,h,d)
        f1,q1=generic_scatter(updated,roles,ts,h,d)
        delta=image_conditioned_fused_delta_fastpath(dirty,updated,roles,ts,h,d)
        need(checked_fused_delta(g,dirty,updated,roles,ts,h,d)==delta,"complete guard disagrees")
        need(delta==xs,"fused correction differs from identity")
        need([sub(y,x) for x,y in zip(f0,f1)]==xs,"old/new Fraction reference differs")
        need([add(x,y) for x,y in zip(oldout,delta)]==
             [add(x,y) for x,y in zip(oldout,xs)],"dirty output update differs")
        need([sub(y,x) for x,y in zip(fresh,updated)]==dirty,"auxiliary restoration failed")
        generic_max=max(generic_max,q0,q1)
        controls.append(dict(trial=trial,targets=len(ts),generic_extra_fraction_bits=max(q0,q1),
                             fused_extra_fraction_bits=0,dirty_input_and_output=True))
    # The producer-image promise cannot be dropped: a single arbitrary B
    # center has N=1, so N/(-32) is not an exact integer divide.
    off=[(0,0)]*g['q']; off[roles['B',d]]=(1,0)
    rejected=False
    try: image_conditioned_fused_delta_fastpath([(0,0)]*g['q'],off,roles,ts,h,d)
    except AssertionError: rejected=True
    need(rejected,"off-image exact division was accepted")
    offref,offbits=generic_scatter(off,roles,ts,h,d)
    need(offbits==6 and any(grid_bits(z)==6 for z in offref),"off-image precision witness absent")
    # Unmatched physical phase frames also invalidate subtract-before-divide:
    # with no fresh source, rotate one dirty B role from 1 to i. Its apparent
    # difference is i-1, which does not lie in the producer's image.
    phase_before=[(0,0)]*g['q']; phase_before[roles['B',d]]=(1,0)
    phase_after=list(phase_before); phase_after[roles['B',d]]=(0,1)
    phase_rejected=False
    try: image_conditioned_fused_delta_fastpath(phase_before,phase_after,roles,ts,h,d)
    except AssertionError: phase_rejected=True
    need(phase_rejected,"mismatched phase-frame difference was accepted")
    # All local quotient checks can succeed off-image. A single side A root
    # equal to 2 produces one legal candidate X=1, but omits that source's
    # required center and side outputs. Only the full P(Q(delta)) guard sees it.
    divisible_off=[(0,0)]*g['q']; divisible_off[roles['A',ts[0]]]=(2,0)
    zero=[(0,0)]*g['q']
    candidate=image_conditioned_fused_delta_fastpath(zero,divisible_off,roles,ts,h,d)
    need(candidate[0]==(1,0) and numeric_roots(g,candidate)!=divisible_off,
         "divisible off-image witness missing")
    membership_rejected=False
    try: checked_fused_delta(g,zero,divisible_off,roles,ts,h,d)
    except AssertionError: membership_rejected=True
    need(membership_rejected,"complete membership guard accepted divisible off-image input")
    # Even when old/new frames match on each role, mutually different role
    # phases need not preserve the ONE common scalar producer image.
    impulse_index=ts.index((0,1,d))
    impulse=[(0,0)]*len(ts); impulse[impulse_index]=(1,0)
    per_role_phase=numeric_roots(g,impulse)
    z=per_role_phase[roles['B',d]]
    per_role_phase[roles['B',d]]=(-z[1],z[0])
    incoherent_rejected=False
    try: checked_fused_delta(g,zero,per_role_phase,roles,ts,h,d)
    except AssertionError: incoherent_rejected=True
    need(incoherent_rejected,"incoherent matched role phases accepted")
    # Zip must not silently discard unmatched complete-stream ports.
    for bad in (zero[:-1],zero+[(0,0)]):
        bad_rejected=False
        try: checked_fused_delta(g,bad,zero,roles,ts,h,d)
        except AssertionError: bad_rejected=True
        need(bad_rejected,"wrong complete port count accepted")
    fractional_port=list(zero); fractional_port[0]=(Q(1,2),0)
    bad_rejected=False
    try: checked_fused_delta(g,zero,fractional_port,roles,ts,h,d)
    except AssertionError: bad_rejected=True
    need(bad_rejected,"unscaled fractional numerator accepted")
    # A forgotten identity term must change a complete scalar coefficient.
    need(any((j-1+int(j==0))/2 != int(j==3) for j in range(4)),"negative coefficient control")
    raw_calls=2*(1+1+(h-d)+d+(g['q']-h))
    fused_calls=1+(h-d)+len(ts)
    report=dict(status='passed',upstream_commit=PIN,source_sha256=expected_hashes,
        source_manifest_sha256=sha(a.sources),source_mode='external pinned Git checkout' if external else 'bundled source with expected hashes',
        generated_producer=generated,independent_image=image,controls=controls,
        exact_coefficient_identity="j-1+[j=0]-[j=2] = 2[j=3]",
        recover_total_identity="sum B - 2 sum D = -32 T",
        maximum_generic_fraction_bits=generic_max,maximum_fused_fraction_bits=0,
        reference_gaussian_quotient_calls=raw_calls,fused_gaussian_quotient_calls=fused_calls,
        operation_count_scope="these two explicit common-frame reference schedules; not optimality or physical-network runtime",
        complete_membership_guard=dict(predicate="P(Q(delta))=delta after integer-exact Q",
            extra_gaussian_additions_per_call=g['n']-g['v']-1,
            verified_source_image_fastpath="skip regeneration only with supplied delta=P(X) certificate",
            tested_dirty_cases=len(controls)),
        negatives=dict(off_image_rejected=True,off_image_fraction_bits=offbits,
                       missing_intersection_two_correction_rejected=True,
                       unmatched_phase_frame_rejected=True,
                       locally_divisible_off_image_rejected_by_full_guard=True,
                       individually_matched_but_incoherent_role_phases_rejected=True,
                       wrong_complete_port_count_rejected=True,
                       unscaled_fractional_numerator_rejected=True),
        artifacts_sha256={p.name:sha(p) for p in a.output.glob('mixed28.*')},
        elapsed_seconds=round(time.perf_counter()-started,3),
        scope="all-input integer scalar image identities plus finite dirty-input controls; no phase-frame/tape/asymptotic rewrite")
    (a.output/'receipt.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps({k:v for k,v in report.items() if k not in ('source_sha256','generated_producer','artifacts_sha256')},indent=2))

if __name__=='__main__': main()
