import DyadicCertificates
import GaussianLattice

#print axioms GaussianParity.GInt.ext
#print axioms GaussianParity.residue_zero_iff
#print axioms GaussianParity.dividePi_exact_iff
#print axioms GaussianParity.dividePi_mulPi
#print axioms GaussianParity.butterfly_integral_iff
#print axioms GaussianParity.butterfly_exact
#print axioms GaussianParity.butterfly_sameResidue
#print axioms GaussianParity.butterfly_square
#print axioms GaussianParity.residue_mulI
#print axioms GaussianParity.residue_add
#print axioms GaussianParity.residue_mulPi
#print axioms GaussianParity.component_parity_implies_sameResidue
#print axioms GaussianParity.cross_parity_example
#print axioms GaussianParity.changed_pairing_obstruction
#print axioms GaussianParity.piIter_mulPi
#print axioms GaussianParity.piIter_add
#print axioms GaussianParity.piIter_commute
#print axioms GaussianParity.mulPi_injective
#print axioms GaussianParity.piIter_injective
#print axioms GaussianParity.SameValue.refl
#print axioms GaussianParity.SameValue.symm
#print axioms GaussianParity.SameValue.trans
#print axioms GaussianParity.certifiedButterfly_contract
#print axioms GaussianParity.certifiedButterfly_refines
#print axioms GaussianParity.certifiedButterfly_exponent_bound
#print axioms GaussianParity.inverseButterfly_eq_swap
#print axioms GaussianParity.inverseButterfly_after
#print axioms GaussianParity.butterfly_fourth
#print axioms GaussianParity.doubleButterfly_joint_parity
#print axioms GaussianParity.sharedDefect_is_bit
#print axioms GaussianParity.sharedDefect_zero_iff
#print axioms GaussianParity.shared_defect_reconstruction
#print axioms GaussianParity.doubleButterfly_exact
#print axioms GaussianParity.halfHadamard_exact_iff
#print axioms GaussianParity.cross_parity_fails_halfHadamard
#print axioms GaussianParity.raiseTo_sameValue
#print axioms GaussianParity.alignedButterfly_input_exact
#print axioms GaussianParity.alignedButterfly_refines
#print axioms GaussianParity.mulPi_square
#print axioms GaussianParity.mulI_scale
#print axioms GaussianParity.scale_mul
#print axioms GaussianParity.repeatPi_even
#print axioms GaussianParity.mulI_negI
#print axioms GaussianParity.negI_mulI
#print axioms GaussianParity.repeatI_commute
#print axioms GaussianParity.repeatI_negI_commute
#print axioms GaussianParity.repeatI_cancel
#print axioms GaussianParity.mulPi_scale
#print axioms GaussianParity.repeatPi_odd
#print axioms GaussianParity.pi_even_ideal
#print axioms GaussianParity.pi_odd_ideal
#print axioms GaussianParity.odd_ideal_parity
#print axioms GaussianParity.pi_not_binary_one
#print axioms GaussianParity.even_binary_conversion
#print axioms GaussianParity.odd_binary_conversion
#print axioms GaussianParity.residue_negI
#print axioms GaussianParity.repeatNegI_residue
#print axioms GaussianParity.odd_binary_numerator_parity
#print axioms GaussianParity.binary_grid_conversion
#print axioms GaussianParity.binary_one_residue_zero
#print axioms GaussianParity.even_impulse_primitive
#print axioms GaussianParity.bothOdd_negI
#print axioms GaussianParity.bothOdd_repeatNegI
#print axioms GaussianParity.odd_impulse_primitive
#print axioms GaussianParity.scale_injective
#print axioms GaussianParity.even_grid_sharp
#print axioms GaussianParity.odd_grid_sharp
#print axioms GaussianParity.gaussianMul_pi_pi
#print axioms GaussianParity.two_pi_factors_binary
