#!/usr/bin/env python3
"""Exact assembly accounting for a supplied h=24 pair-star complex interface.

This file does not prove the new scalar circuit or its binary phase contract.
Those construction obligations must be proved separately. The retained
compact-control machinery is used without a change to its cost proof.
"""
from fractions import Fraction as Q
from pathlib import Path
import hashlib
import json
from math import comb

from certify import Parameters, constraints, margins, require, verify_sources
from compact_control_layer import layer_exponents
from paired_network import BIT_SAVING
from prepare_layers import serializable
from search_network import log_integer_bounds, log_ratio_bounds

ROOT = Path(__file__).resolve().parents[1]
COMPLEX_SAVING = Q(4, 10**9)
BETA = Q(1, 10)
ZETA = Q(1, 100)
RELATIVE_LAYER_GAP = Q(1, 10**12)
KAPPA = Q(5919999985, 10**19)
SHARP_BIT_SAVING = Q(29646101715649, 10**22)
SHARP_KAPPA = Q(5929220328, 10**19)


def supplied_counts():
    """Numbers supplied by the separate pair-star circuit derivation."""
    h = 24
    m, v = h**3, comb(h, 3)
    N = v**3
    W = 4496369044992
    L = 7078883328
    s = W*m-2*N+2*L
    return dict(h=h, m=m, v=v, N=N, Wc=W, Lc=L, sc=s)


def guard_from_counts(n, beta=BETA, zeta=ZETA):
    """The existing generalized guard, with the new network's actual counts."""
    require(0 < beta < 1 and zeta > 0, 'Invalid guard parameters')
    m, W, s = n['m'], n['Wc'], n['sc']
    require(m >= 3 and 2 <= s < m**5, 'Coefficient-depth hypothesis failed')
    E = 64*(W+m+1)**3
    B = s+E
    require(s*(8+E) <= 9*B*B, 'One-piece guard charge failed')
    C1 = 5-4*beta+zeta
    raw = max(Q(128*m*B*B), 18*m*B*B*(1+1/zeta))
    C0 = -(-raw.numerator//raw.denominator)
    require(9*m*B*B*(1+1/zeta)+18 <= C0, 'Whole-layer guard failed')
    return dict(m=m, W=W, s=s, E=E, B=B, beta=beta, zeta=zeta,
                C0=C0, C1=C1, one_piece_exponent=5-4*beta)


def optimized_parameters():
    a, t = BIT_SAVING, RELATIVE_LAYER_GAP
    return Parameters(
        tau=1-a, sigma=1-COMPLEX_SAVING,
        epsilon=Q(399999999, 2000000000), c=Q(1),
        lam=1-a*(1-t/2), lamp=1-a*(1-t),
        kappa=KAPPA, beta=BETA, delta=Q(1, 10**12),
        C1=5-4*BETA+ZETA,
    )


def simple_parameters():
    return Parameters(
        tau=1-BIT_SAVING, sigma=1-COMPLEX_SAVING,
        epsilon=Q(19999, 100000), c=Q(1),
        lam=1-Q(5919, 2*10**12), lamp=1-Q(2959, 10**12),
        kappa=Q(59, 10**11), beta=Q(1, 4), delta=Q(1, 10**6),
        C1=Q(401, 100),
    )


def sharpened_bit_certificate():
    """Improve only the exponent certified for the retained paired bit graph.

    Its stored counts are regenerated by the retained paired-network checker;
    explicitly check their exact eta and rank formula before using them.
    """
    path = ROOT/'certificates/paired-network.json'
    baseline = json.loads(path.read_text())
    n = {key: Q(value) for key, value in baseline['bit_counts'].items()}
    require(n['h'] == 50 and n['m'] == 125000, 'Unexpected retained bit network')
    eta = (n['W']*n['m']-n['s'])/(n['W']*n['m'])
    require(eta == n['eta'] == Q(23, 661055000), 'Retained bit deficit mismatch')
    require(n['W']*n['m']-n['s'] == n['N']-2*n['L'] == n['D'],
            'Retained bit residual formula mismatch')
    log_lo, log_hi = log_integer_bounds(int(n['m']))
    numerator_lower = eta+eta*eta/2
    proof_gap = numerator_lower-SHARP_BIT_SAVING*log_hi
    require(proof_gap > 0, 'Sharpened bit exponent lacks a strict proof')
    neg_lo, neg_hi = log_ratio_bounds(1/(1-eta), terms=3)
    saving_lo, saving_hi = neg_lo/log_hi, neg_hi/log_lo
    require(SHARP_BIT_SAVING < saving_lo, 'Sharpened bit exponent exceeded graph')
    return dict(
        saving=SHARP_BIT_SAVING, counts=n, eta=eta,
        log_m_enclosure=(log_lo, log_hi), negative_log_lower=numerator_lower,
        proof_gap=proof_gap, actual_saving_enclosure=(saving_lo, saving_hi),
        source_certificate='certificates/paired-network.json',
        source_certificate_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
        scope='Same retained paired h50 bit graph; sharpened exponent comparison only.',
    )


def sharpened_parameters():
    a, t = SHARP_BIT_SAVING, RELATIVE_LAYER_GAP
    return Parameters(
        tau=1-a, sigma=1-COMPLEX_SAVING,
        epsilon=Q(399999999, 2000000000), c=Q(1),
        lam=1-a*(1-t/2), lamp=1-a*(1-t),
        kappa=SHARP_KAPPA, beta=BETA, delta=Q(1, 10**12),
        C1=5-4*BETA+ZETA,
    )


def normalized_counts(n):
    """Accept either the network's W,L,s names or the legacy Wc,Lc,sc."""
    result = dict(n)
    result.setdefault('v', comb(result['h'], 3))
    result.setdefault('m', result['h']**3)
    result.setdefault('N', result['v']**3)
    for legacy, plain in (('Wc', 'W'), ('Lc', 'L'), ('sc', 's')):
        if legacy not in result and plain in result:
            result[legacy] = result[plain]
    result.setdefault('sc', result['Wc']*result['m']-2*result['N']+2*result['Lc'])
    return result


def check(p, n, zeta=ZETA, *, sharpened_bit=False):
    n = normalized_counts(n)
    require(n['m'] == n['h']**3 and n['v'] == comb(n['h'], 3),
            'Ground-size count mismatch')
    require(n['N'] == n['v']**3 and 0 <= n['Lc'] < n['N'],
            'Nonpositive complex saving')
    require(n['sc'] == n['Wc']*n['m']-2*n['N']+2*n['Lc'],
            'Residual formula mismatch')
    eta = Q(2*(n['N']-n['Lc']), n['Wc']*n['m'])
    log_lo, log_hi = log_integer_bounds(n['m'])
    bit_limit = (sharpened_bit_certificate()['saving']
                 if sharpened_bit else BIT_SAVING)
    require(0 < 1-p.tau <= bit_limit, 'Uncertified bit saving')
    require(0 < 1-p.sigma and eta > (1-p.sigma)*log_hi,
            'Uncertified complex saving')
    neg_lo, neg_hi = log_ratio_bounds(1/(1-eta), terms=3)
    complex_lo, complex_hi = neg_lo/log_hi, neg_hi/log_lo
    g = guard_from_counts(n, p.beta, zeta)
    require(g['C1'] == p.C1, 'Guard/parameter mismatch')
    exponents = layer_exponents(p.tau, p.sigma, p.beta, p.c)
    slacks = constraints(p, layout_model='nonadjacent',
                        assembly_model='tight-gaussian')
    slacks['packed_overhead'] = p.lam-exponents['internal']
    slacks['reserved_axes'] = p.lamp-exponents['preprocessing']
    for name, value in slacks.items():
        require(value > 0, 'Failed exact constraint: '+name)
    gs = margins(p, layout_model='nonadjacent', assembly_model='tight-gaussian')
    minimum = min(gs.values())
    require(minimum > p.kappa, 'No strict final absorption gap')
    return dict(parameters=vars(p), guard=g, recurrence=exponents,
                complex_saving_enclosure=(complex_lo, complex_hi),
                complex_eta=eta,
                complex_exponent_proof_gap=eta-(1-p.sigma)*log_hi,
                constraint_slacks=slacks, margins=gs,
                minimum_margin=minimum, absorption_gap=minimum-p.kappa)


def certificate(counts=None):
    n = normalized_counts(supplied_counts() if counts is None else counts)
    p = optimized_parameters()
    main = check(simple_parameters(), n)
    optimized = check(p, n)
    sharp = sharpened_parameters()
    sharpened = check(sharp, n, sharpened_bit=True)
    bit_proof = sharpened_bit_certificate()
    ceiling = BIT_SAVING/(5+4*BIT_SAVING)
    sharp_ceiling = SHARP_BIT_SAVING/(5+4*SHARP_BIT_SAVING)
    bit_lo, bit_hi = bit_proof['actual_saving_enclosure']
    actual_ceiling = (bit_lo/(5+4*bit_lo), bit_hi/(5+4*bit_hi))
    require(Q(1, 2**31) < p.kappa < ceiling < Q(1, 2**30),
            'Unexpected dyadic scale')
    # Since a_c > a_b and (1-beta)*a_c > a_b, the stopped leaves
    # permit q -> a_b. With c=1, g2 >= g3, while the Gaussian margin
    # yields the sharp retained-bit ceiling a_b/(5+4*a_b).
    require((1-p.beta)*(1-p.sigma) > BIT_SAVING,
            'Complex leaves would bind before the claimed bit ceiling')
    require((1-sharp.beta)*(1-sharp.sigma) > bit_hi,
            'Complex leaves would bind before the actual bit-graph ceiling')
    require(p.kappa < sharp.kappa < sharp_ceiling < Q(1, 2**30),
            'Sharpened witness has an unexpected scale')
    files = ['notes/compact-control-movement.tex',
             'notes/compact-control-layout.tex',
             'notes/compact-control-guard.tex']
    return dict(
        status='CONDITIONAL ON THE NEW PAIR-STAR COMPLEX INTERFACE PROOF',
        upstream_commit=verify_sources(),
        supplied_network_counts=n,
        main=main,
        optimized=optimized,
        sharpened=sharpened,
        sharpened_bit_exponent=bit_proof,
        retained_bit_and_assembly_supremum=ceiling,
        sharpened_bit_and_assembly_supremum=sharp_ceiling,
        actual_bit_graph_and_assembly_supremum_enclosure=actual_ceiling,
        supremum_gap=ceiling-p.kappa,
        sharpened_supremum_gap=sharp_ceiling-sharp.kappa,
        main_improvement_over_current=simple_parameters().kappa/Q(83, 10**12),
        optimized_improvement_over_current=p.kappa/Q(83, 10**12),
        sharpened_improvement_over_current=sharp.kappa/Q(83, 10**12),
        proof_sha256={name: hashlib.sha256((ROOT/name).read_bytes()).hexdigest()
                      for name in files},
        c_equals_one_argument=(
            'K=d; front/back reservation counts are O(log p), while row '
            'reservations are O(log d). Thus all reservations are o(d). '
            'Their preprocessing exponent max(1-c,0) is zero, absorbed '
            'strictly by lambda_prime; epsilon*(1+c)<1 still gives K=o(ell).'),
        verification_boundary=(
            'Checks exact motif counts, logarithms, guard arithmetic, every '
            'retained parameter constraint and all seven assembly margins. '
            'It does not establish the new scalar circuit, binary residual '
            'bases, signed endpoints, or any retained upstream theorem.'),
    )


if __name__ == '__main__':
    result = certificate()
    (ROOT/'certificates/complex_pair_star_parameters.json').write_text(
        json.dumps(serializable(result), indent=2, sort_keys=True)+'\n')
    print('PASS simple conditional pair-star assembly:', simple_parameters().kappa, '> 2^-31')
    print('PASS optimized conditional pair-star assembly:', KAPPA, '> 2^-31')
    print('PASS sharpened-bit conditional pair-star assembly:', SHARP_KAPPA, '> 2^-31')
    print('Sharpened-bit minimum margin:', result['sharpened']['minimum_margin'])
    print('Sharpened-bit absorption gap:', result['sharpened']['absorption_gap'])
    print('Exact certified-bit ceiling:', result['sharpened_bit_and_assembly_supremum'])
