#!/usr/bin/env python3
"""Exact partial-swap moments and assembly, conditional on the written interfaces.

Copyright 2026 icekylinx. Apache-2.0.
Prepared with substantial OpenAI GPT-6 Astra and Codex assistance.
Producer data are independently regenerated by partial_swap_producer.py.
"""
import argparse
from collections import Counter
from dataclasses import asdict
from fractions import Fraction as Q
from hashlib import sha256
import json
from math import comb, prod
from pathlib import Path

from certify import Parameters, require
from compact_control_layer import layer_exponents
from fast_gaussian import fast_constraints, fast_margins
from prepare_layers import serializable

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / 'certificates/partial-swap-input.json'
BIT_SAVING = Q(188459, 50000000000)
COMPLEX_SAVING = Q(417, 100000000)
KAPPA = Q(942293, 500000000000)


def log_upper(value):
    value = Q(value)
    require(value >= 1, 'Log argument below one')
    power = 0
    while value > 2:
        value /= 2
        power += 1
    def series(x):
        z = (x-1)/(x+1)
        return 2*sum((z**(2*j+1)/(2*j+1) for j in range(24)), Q(0)) + 2*z**49/(49*(1-z*z))
    scaled = (power*series(Q(2)) + series(value))*10**12
    return Q(-(-scaled.numerator//scaled.denominator), 10**12)


def moment(m, W, rows, saving, sharp):
    upper = Q(0)
    logs = {}
    for t, count in sorted(rows.items()):
        require(0 < t < m and count >= 0, 'Invalid recursive child')
        ell = log_upper(Q(m, t))
        u = saving*ell
        require(0 <= u < 1, 'Exponential enclosure outside range')
        bound = 1+u+u*u/(2*(1-u/3)) if sharp else 1/(1-u)
        upper += Q(count*t, W*m)*bound
        logs[str(t)] = ell
    require(upper < 1, 'Characteristic moment does not contract')
    return dict(saving=saving, exponent=1-saving, moment_upper=upper,
                strict_gap=1-upper, logarithm_upper_bounds=logs,
                child_width_multiplicities=sorted(rows.items()),
                enclosure='1+u+u^2/(2(1-u/3))' if sharp else '1/(1-u)')


def bit_counts(d):
    dims = (25, 23, 57)
    ps = d['producers']
    v = [comb(h, 3) for h in dims]
    N, m = prod(v), prod(dims)
    banks = [N//vi*ps[str(h)]['roles'] for h, vi in zip(dims, v)]
    B1, B2, B3 = banks
    E = B3-B1
    require(E >= 0, 'Stage-three bank must accommodate stage one')
    W = 2*N+B2+B3
    L = N*sum((Q(6, h-2) for h in dims), Q(0))
    require(L.denominator == 1, 'Nonintegral retained loss')
    L = int(L)
    s = W*m-2*N+2*L
    rows = Counter()
    profiles = [(B1, (25,7,25,25,32611)), (E,(57,32661)),
                (B2,(575,31625)), (B2,(23,529)),
                (2*N,(55,463,31513)), (2*N,(481,)),
                (2*N,(1,23)), (2*N,(1,21)), (2*N,(1,55))]
    rows[1] += 2*N*(113+47)
    for count, profile in profiles:
        for t in profile:
            rows[t] += count
    for h, vi in zip(dims, v):
        p = ps[str(h)]
        require(p['v'] == vi and p['outputs'] == 3*vi+h, 'Producer dimensions')
        require(p['roles'] == p['additions']+p['outputs']-p['matches'], 'Role count')
        require(p['loss'] == h*(h-1), 'Producer retained loss')
        hist = p['histogram']
        require(len(hist) == h+1 and all(n >= 0 for n in hist), 'Histogram range')
        require(sum(r*n for r,n in enumerate(hist)) == h*p['roles']+2*h*(h-1), 'Internal rank mass')
        for r,n in enumerate(hist):
            copies = N//vi*n
            block = max(0, 2*r-h)
            rows[1] += copies*(r-block)
            if block:
                rows[block] += copies
    computed = dict(m=m,N=N,B1=B1,B2=B2,B3=B3,E=E,W=W,L=L,s=s,
                    deficit=W*m-s,eta=Q(W*m-s,W*m),singletons=rows[1])
    for name,value in computed.items():
        require(value == Q(d['parameters'][name]), 'Recorded bit count differs: '+name)
    require(sorted((t,n) for t,n in rows.items() if t>1) == [tuple(x) for x in d['bit_bulk_width_multiplicities']], 'Recorded bit multiset differs')
    require(sum(t*n for t,n in rows.items()) == s, 'Complete bit rank mass')
    return computed, rows


def complex_counts(d):
    p = d['complex']
    h=28; v=comb(h,3); m=h**3; N=v**3
    B=v*v*(93838+h+1); W=2*N+2*B
    s=W*m-2*N+6*v*v*h*(h+1)
    macros=[(m-2*h,B),(m-h*h,B),((h*h-1)*(h-1),2*N),
            (h*(h-1),B-N),((h-1)**2,3*N)]
    require(macros == [tuple(x) for x in p['macro_width_multiplicities']], 'Complex macro profiles')
    hist=p['histogram']
    require(sum(r*n for r,n in enumerate(hist)) == h*(93838+h+1)+2*h*(h+1), 'Complex internal rank mass')
    rows=Counter(dict(macros))
    for r,n in enumerate(hist):
        if r>=2:
            rows[r] += 3*v*v*n
    # The remaining physical and macro singleton transitions are fixed by the
    # retained full rank budget; the internal histogram is regenerated separately.
    rows[1]=s-sum(t*n for t,n in rows.items())
    counts=dict(h=h,v=v,m=m,N=N,B=B,W=W,s=s,singletons=rows[1])
    for name,value in counts.items():
        require(value == int(p[name]), 'Recorded complex count differs: '+name)
    return counts, rows


def guard(n):
    m=n['m']; W=n['W']; h=n['h']; q=m+6*h
    rho=Q(6,5); gamma=Q(4999,5000); lower=160000
    require(lower**5 < m**6 and 28 < 2**5 and 756 < 4**5, 'Guard power bounds')
    t=Q(56,m)
    # Taylor integral remainder: (1-t)^(6/5) <= 1-6t/5+3t²/[25(1-t)].
    power=1-Q(6,5)*t+Q(3,25)*t*t/(1-t)
    bounds=dict(largest=power+Q(2*(q-(m-56)),lower),
                other_large=Q(27,28)+Q(4*979,lower),
                no_large=Q(4*q,lower))
    require(all(2*r>q for r in (21896,21168,21141)), 'Two large edges on a path')
    require(q-21896 < 729, 'Largest-edge remainder admits medium edge')
    require(max(bounds.values()) < gamma, 'Precision path does not contract')
    E=64*(W+m+1)**3
    require(36*W**3+4*n['s']+4*W+8*m+4 < E, 'Local coefficient allowance')
    dep=5000*(E+16*m+1)
    beta=Q(1,1000); zeta=Q(1,10000)
    raw=128*m*(1+1/zeta)*dep
    C0=-(-raw.numerator//raw.denominator)
    require(dep*(1-gamma)>=E and dep>=16*m, 'Depth induction allowance')
    require(m*(1+1/zeta)*dep+18<=C0, 'Layer allowance')
    return dict(q=q,rho=rho,gamma=gamma,path_moment_upper=bounds,
                strict_gap=gamma-max(bounds.values()),E=E,dependency_constant=dep,
                C0=C0,C1=rho-(rho-1)*beta+zeta)


def parameters():
    tau=1-BIT_SAVING
    return Parameters(tau=tau,sigma=1-COMPLEX_SAVING,
        epsilon=1/(2+BIT_SAVING),c=Q(1),beta=Q(1,1000),delta=Q(1,10**16),
        lam=tau+Q(1,10**20),lamp=tau+Q(2,10**20),C1=Q(11999,10000),kappa=KAPPA)


def assembly(p=None):
    p=parameters() if p is None else p
    ex=layer_exponents(p.tau,p.sigma,p.beta,p.c)
    cs=fast_constraints(p)
    cs['packed_overhead']=p.lam-ex['internal']
    cs['reserved_axes']=p.lamp-ex['preprocessing']
    require(len(cs)==29 and all(v>0 for v in cs.values()), 'Strict assembly constraint')
    margins=fast_margins(p)
    require(len(margins)==7 and min(margins.values())>p.kappa, 'Strict assembly absorption')
    return dict(parameters=asdict(p),recurrence=ex,constraints=cs,margins=margins,
                minimum_margin=min(margins.values()),absorption_gap=min(margins.values())-p.kappa)


def basis_combinatorics():
    a,b,k=25,23,57; H=a*b; size=k+a
    R=list(range(a))+list(range(7))+list(range(a))*2
    C=list(range(a))*2+list(range(7))+list(range(a))
    completions=[]
    for beta in range(b):
        prescribed={}
        def set_entry(row,col):
            require(row not in prescribed or prescribed[row]==col, 'Conflicting prescribed row')
            require(col not in prescribed.values() or prescribed.get(row)==col, 'Conflicting prescribed column')
            prescribed[row]=col
        for i,label in enumerate(R):
            if i%b==beta: set_entry(i//b,label)
        for j,label in enumerate(C):
            i=H-size+j
            if i%b==beta: set_entry(i//b,label)
        unused=iter(c for c in range(a) if c not in prescribed.values())
        completions.append([prescribed[r] if r in prescribed else next(unused) for r in range(a)])
    forward=[(0,23),(1,24)]+[((j+2)%23,j) for j in range(7)]+[((j+9)%23,j) for j in range(15)]
    dual=[(23,0),(24,1)]+[(2+((-9+j)%23),j) for j in range(7)]+[(2+((-11+j)%23),j) for j in range(10,25)]
    for edges in (forward,dual):
        require(len(edges)==24, 'Tree edge count')
        seen={0}
        while True:
            expanded=seen|{y for x,y in edges if x in seen}|{x for x,y in edges if y in seen}
            if expanded==seen:break
            seen=expanded
        require(seen==set(range(25)), 'A5 incidence graph disconnected')
    return dict(row_labels=R,inverse_column_labels=C,permutation_completions=completions,
                A5_forward_tree=forward,A5_dual_tree=dual,
                scope='Prescription compatibility and A5 trees; remaining generic minors are proved in the note.')


def certificate():
    d=json.loads(INPUT.read_text())
    bn,br=bit_counts(d); cn,cr=complex_counts(d)
    bit=moment(bn['m'],bn['W'],br,BIT_SAVING,True)
    comp=moment(cn['m'],cn['W'],cr,COMPLEX_SAVING,False)
    require(bit['strict_gap']>Q(617,10**16), 'Bit gap lower bound')
    require(comp['strict_gap']>Q(23982,10**15), 'Complex gap lower bound')
    a=assembly(); g=guard(cn)
    require(g['C1']==a['parameters']['C1'], 'Guard exponent mismatch')
    require(a['absorption_gap']>Q(44822,10**17), 'Assembly gap lower bound')
    sources=[INPUT,Path(__file__).resolve(),ROOT/'scripts/partial_swap_producer.py']
    sources += sorted(p for p in (ROOT/'scripts/partial_swap').iterdir() if p.is_file())
    sources += sorted((ROOT/'notes').glob('partial-swap-*.tex'))
    return dict(status='Conditional partial-swap integer-multiplication witness',
        kappa=KAPPA,bit=dict(counts=bn,**bit),complex=dict(counts=cn,**comp),
        basis_combinatorics=basis_combinatorics(),guard=g,assembly=a,
        source_sha256={str(p.relative_to(ROOT)):sha256(p.read_bytes()).hexdigest() for p in sources},
        inherited_PR10_commit='62691e395a0458ce089a1c7b5d89e74291e95e29',
        scope='Exact finite arithmetic and basis combinatorics. Producer regeneration is separate. '
              'The common-basis, recursion, and retained analytic/tape arguments remain written proofs.')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=ROOT/'certificates/partial-swap-network.json')
    args=parser.parse_args()
    result=certificate()
    args.output.write_text(json.dumps(serializable(result),indent=2,sort_keys=True)+'\n')
    print('PASS partial-swap kappa='+str(KAPPA)+' = 1.884586e-6')
    print('29 strict constraints; 7 strict assembly margins; bit/complex moments and precision guard')

if __name__=='__main__':
    main()
